version: '3.9'

services:
  django:
    build: ./project
    working_dir: /project
    #command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi:application"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project:/project
      - static_data:/project/static
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://django:django-QWErty!2@db:5432/django
      - DEBUG=1
  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django-QWErty!2
      - POSTGRES_DB=django
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "82:80"
    volumes:
      - static_data:/var/www/html/static/
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./nginx-conf.d/cert.pem:/etc/cert.pem
      - ./nginx-conf.d/key.pem:/etc/key.pem
volumes:
  pg_data:
  static_data:
