version: '3.9'

services:
  django:
    build: ./project
    command: sh -c "cd project; gunicorn --bind 0.0.0.0:8000 app.wsgi:application"
    volumes:
      - ./project:/project
      - static_data:/project/static
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://django:django-QWErty!2@db:5432/django
      - DEBUG=1
  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django-QWErty!2
      - POSTGRES_DB=django
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/var/www/html/static/
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
  certbot:
    depends_on:
      - nginx
    ports:
      - "6000:80"
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: "wlovemrock@gmail.com"
        DOMAIN_URL: "test-tema-yo-kruto.site"
volumes:
  pg_data:
  static_data:
