# Generated by Django 5.0.7 on 2024-07-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('suburl', models.CharField(db_index=True, max_length=255)),
                ('amo_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
