# Generated by Django 5.0.7 on 2024-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "suburl",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("amo_id", models.PositiveBigIntegerField(unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("amo_token", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
