# Generated by Django 5.0.7 on 2024-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amo_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='suburl',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
