# Generated by Django 5.0.7 on 2024-07-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_amo_id_alter_project_suburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amo_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
