# Generated by Django 5.0.7 on 2024-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('project_id', models.PositiveBigIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
