# Generated by Django 5.0.7 on 2024-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_amo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_amo_token',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
