# Generated by Django 5.0.7 on 2024-07-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0005_user_last_sub_url_alter_user_amo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='amo_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
