# Generated by Django 5.0.7 on 2024-07-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0006_user_project_alter_user_amo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
