# Generated by Django 5.0.7 on 2024-07-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_amo_token',
            new_name='amo_uuid',
        ),
    ]
